"""Initial schema: all 11 tables

Revision ID: 21856d8e169b
Revises: 
Create Date: 2026-02-21 00:02:08.735794
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '21856d8e169b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abuse_events',
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abuse_events_api_key_id'), 'abuse_events', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_abuse_events_event_type'), 'abuse_events', ['event_type'], unique=False)
    op.create_table('abuse_scores',
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('scan_count_1h', sa.Integer(), nullable=False),
    sa.Column('flagged_ratio', sa.Float(), nullable=False),
    sa.Column('similarity_ratio', sa.Float(), nullable=False),
    sa.Column('entity_reuse_ratio', sa.Float(), nullable=False),
    sa.Column('response_level', sa.String(length=10), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('api_key_id')
    )
    op.create_table('api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_table('reports',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_feedback_type'), 'reports', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_reports_scan_id'), 'reports', ['scan_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('scam_cards',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('short_id', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=15), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('scam_type', sa.String(length=30), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scam_cards_scan_id'), 'scam_cards', ['scan_id'], unique=True)
    op.create_index(op.f('ix_scam_cards_short_id'), 'scam_cards', ['short_id'], unique=True)
    op.create_table('scam_types',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('severity_default', sa.String(length=10), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('scan_entities',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('normalized_value', sa.String(length=2048), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_entities_scan_id'), 'scan_entities', ['scan_id'], unique=False)
    op.create_table('scans',
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.SmallInteger(), nullable=True),
    sa.Column('risk_level', sa.String(length=15), nullable=True),
    sa.Column('scam_type', sa.String(length=30), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('checks_performed', sa.JSON(), nullable=True),
    sa.Column('checks_not_available', sa.JSON(), nullable=True),
    sa.Column('confidence_note', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('content_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_api_key_id'), 'scans', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_scans_content_hash'), 'scans', ['content_hash'], unique=False)
    op.create_table('semantic_fingerprints',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('scam_type', sa.String(length=30), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_fingerprints_api_key_id'), 'semantic_fingerprints', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_semantic_fingerprints_fingerprint'), 'semantic_fingerprints', ['fingerprint'], unique=False)
    op.create_table('threat_results',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('is_threat', sa.Boolean(), nullable=True),
    sa.Column('threat_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_results_scan_id'), 'threat_results', ['scan_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_threat_results_scan_id'), table_name='threat_results')
    op.drop_table('threat_results')
    op.drop_index(op.f('ix_semantic_fingerprints_fingerprint'), table_name='semantic_fingerprints')
    op.drop_index(op.f('ix_semantic_fingerprints_api_key_id'), table_name='semantic_fingerprints')
    op.drop_table('semantic_fingerprints')
    op.drop_index(op.f('ix_scans_content_hash'), table_name='scans')
    op.drop_index(op.f('ix_scans_api_key_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_scan_entities_scan_id'), table_name='scan_entities')
    op.drop_table('scan_entities')
    op.drop_table('scam_types')
    op.drop_index(op.f('ix_scam_cards_short_id'), table_name='scam_cards')
    op.drop_index(op.f('ix_scam_cards_scan_id'), table_name='scam_cards')
    op.drop_table('scam_cards')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_scan_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_feedback_type'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('abuse_scores')
    op.drop_index(op.f('ix_abuse_events_event_type'), table_name='abuse_events')
    op.drop_index(op.f('ix_abuse_events_api_key_id'), table_name='abuse_events')
    op.drop_table('abuse_events')
    # ### end Alembic commands ###
