"""Add foreign key constraints to all models

Revision ID: 4221bd19a9ea
Revises: 21856d8e169b
Create Date: 2026-02-21 00:05:02.721203
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4221bd19a9ea'
down_revision: Union[str, None] = '21856d8e169b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'api_keys', ['api_key_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'scans', ['scan_id'], ['id'])
    op.create_foreign_key(None, 'scam_cards', 'scans', ['scan_id'], ['id'])
    op.create_foreign_key(None, 'scan_entities', 'scans', ['scan_id'], ['id'])
    op.create_foreign_key(None, 'scans', 'api_keys', ['api_key_id'], ['id'])
    op.create_foreign_key(None, 'threat_results', 'scans', ['scan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threat_results', type_='foreignkey')
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.drop_constraint(None, 'scan_entities', type_='foreignkey')
    op.drop_constraint(None, 'scam_cards', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    # ### end Alembic commands ###
